---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Include vars from vars directory
      ansible.builtin.include_vars:
        dir: ./vars
        #dir: ./testing
        extensions: ["yml"]
  roles:
    - {role: infra.aap_configuration.controller_projects, when: controller_projects is defined}
    - {role: infra.aap_configuration.controller_credential_types, when: controller_credential_types is defined}
    - {role: infra.aap_configuration.controller_credentials, when: controller_credentials is defined}
    - {role: infra.aap_configuration.controller_credential_input_sources, when: ccontroller_credential_input_sources is defined}
    - {role: infra.aap_configuration.controller_host_groups, when: controller_groups is defined}
    - {role: infra.aap_configuration.controller_labels, when: controller_labels is defined}
    - {role: infra.aap_configuration.controller_job_templates, when: controller_templates is defined}
    - {role: infra.aap_configuration.controller_workflow_job_templates, when: controller_workflows is defined}
